#' 04: Validation Analysis of Market Regimes
#'
#' @description
#' This script performs validation and exploratory analysis of market
#' regimes generated by `03_regime_modeling.R`. It computes return and
#' risk statistics, analyzes regime durations, calculates cumulative
#' performance, and evaluates a simple regime-based trading strategy.
#'
#' @details
#' **Key steps performed:**
#'
#' 1. **Sanity check**
#'    - Ensures `econ_regime` column exists in `df_regimes`.
#'    - Filters out rows with missing economic regime labels.
#'
#' 2. **Return statistics by regime**
#'    - Computes mean, median, standard deviation, and skewness
#'      of log returns for each economic regime.
#'
#' 3. **Risk metrics by regime**
#'    - Computes average rolling volatility (`vol_20`), average drawdown,
#'      and maximum drawdown per regime.
#'
#' 4. **Regime duration analysis**
#'    - Assigns a unique `regime_id` for each contiguous regime period.
#'    - Computes duration in days for each regime segment.
#'
#' 5. **Cumulative returns**
#'    - Calculates cumulative log returns over the full time series.
#'
#' 6. **Regime-based strategy simulation**
#'    - Simulates a simple strategy: fully invested during Bull regimes,
#'      cash (zero return) otherwise.
#'    - Computes cumulative returns for the strategy.
#'    - Adds a `next_regime` column for forward-looking analysis.
#'
#' 7. **Export for visualization**
#'    - Saves enriched dataset for Tableau or other visualization tools.
#'
#' @dependencies
#' - \pkg{dplyr} for data manipulation
#' - \pkg{tidyr} for data wrangling
#' - \pkg{zoo} for time-series operations
#' - \pkg{moments} for skewness computation
#'
#' @seealso
#' \itemize{
#'   \item `03_regime_modeling.R` for generating regime labels
#'   \item `zoo::lag()` for identifying regime changes
#'   \item `dplyr::group_by()` and `summarise()` for per-regime aggregation
#' }
#'
#' @examples
#' \dontrun{
#' source("04_validation_analysis.R")
#' head(df_analysis)           # Inspect enriched dataset
#' }
NULL

# -----------------------
# Load regime-labeled data
# -----------------------
source("03_regime_modeling.R")

# Load required libraries
library(dplyr)
library(tidyr)
library(zoo)
library(moments)

# -----------------------
# Basic sanity check
# -----------------------
# Ensure the expected column exists
stopifnot("econ_regime" %in% colnames(df_regimes))

# Filter out rows with missing regime labels
df_analysis <- df_regimes %>%
  filter(!is.na(econ_regime))

# -----------------------
# Return statistics by regime
# -----------------------
# Compute mean, median, standard deviation, and skewness per regime
regime_returns <- df_analysis %>%
  group_by(econ_regime) %>%
  summarise(
    mean_return   = mean(log_return, na.rm = TRUE),
    median_return = median(log_return, na.rm = TRUE),
    sd_return     = sd(log_return, na.rm = TRUE),
    skewness      = skewness(log_return, na.rm = TRUE),
    .groups = "drop"
  )

# -----------------------
# Risk metrics by regime
# -----------------------
# Compute average volatility, average drawdown, and maximum drawdown
regime_risk <- df_analysis %>%
  group_by(econ_regime) %>%
  summarise(
    avg_vol        = mean(vol_20, na.rm = TRUE),
    avg_drawdown   = mean(drawdown, na.rm = TRUE),
    max_drawdown   = min(drawdown, na.rm = TRUE),
    .groups = "drop"
  )

# -----------------------
# Regime duration analysis
# -----------------------
# Identify contiguous regime segments
df_analysis <- df_analysis %>%
  mutate(
    regime_id = cumsum(
      econ_regime != lag(econ_regime, default = first(econ_regime))
    )
  )

# Compute duration in days for each regime segment
regime_durations <- df_analysis %>%
  group_by(econ_regime, regime_id) %>%
  summarise(
    duration_days = n(),
    .groups = "drop"
  )

# -----------------------
# Cumulative returns
# -----------------------
# Compute cumulative return for the overall market
df_analysis <- df_analysis %>%
  arrange(DATE) %>%
  mutate(
    cum_return = exp(cumsum(log_return)) - 1
  )

# -----------------------
# Regime-based strategy
# -----------------------
# Strategy: fully invested during Bull regimes, otherwise in cash
df_analysis <- df_analysis %>%
  mutate(
    strategy_log_return = ifelse(
      econ_regime == "Bull",
      log_return,
      0
    ),
    strategy_cum_return = exp(cumsum(strategy_log_return)) - 1
  )

# Add next period's regime for forward-looking analysis
df_analysis <- df_analysis %>%
  mutate(next_regime = lead(econ_regime, 1))

# -----------------------
# Save enriched dataset
# -----------------------
# Export for Tableau or further analysis
write.csv(
  df_analysis,
  "regime_analysis_tableau.csv",
  row.names = FALSE
)
